#!/usr/bin/env python3
import os
import sys
import subprocess
from pathlib import Path

def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <pxr_install_dir>", file=sys.stderr)
        sys.exit(1)

    pxr_dir = sys.argv[1]
    conda_prefix = os.environ.get("CONDA_PREFIX", "")
    build_dir = Path("build")
    build_dir.mkdir(exist_ok=True)

    subprocess.run([
        "cmake", "..",
        "-G", "Ninja",
        "-DCMAKE_BUILD_TYPE=Debug",
        f"-DCMAKE_PREFIX_PATH={conda_prefix};{pxr_dir}",
        f"-DCPLUS_INCLUDE_PATH={conda_prefix}/include/",
    ], cwd=build_dir, check=True)

    subprocess.run(["cmake", "--build", "."], cwd=build_dir, check=True)

    # Generate env.py — cross-platform environment setup script
    env_py = build_dir / "usdsim_env.py"
    conda_lib = str(Path(conda_prefix) / "lib") if conda_prefix else ""
    pxr_lib = str(Path(pxr_dir) / "lib")
    pxr_python = str(Path(pxr_dir) / "lib" / "python")
    build_lib = str(build_dir.resolve() / "lib")

    env_py.write_text('''\
#!/usr/bin/env python3
"""Auto-generated by build.py.

Usage:
  1. As a launcher:  python build/env.py  your_script.py [args...]
  2. As an import:    import env   (with build/ on sys.path or PYTHONPATH)

On Linux, LD_LIBRARY_PATH must be set before the process loads shared libs,
so this module re-execs the current process with the correct environment.
"""
import os, sys

_PATHS = ''' + repr([build_lib, pxr_python]) + '''
_LD_PATHS = ''' + repr([p for p in [conda_lib, pxr_lib, build_lib] if p]) + '''

# 1. Fix sys.path
for p in reversed(_PATHS):
    if p not in sys.path:
        sys.path.insert(0, p)

# 2. Fix LD_LIBRARY_PATH — re-exec if not already set
if sys.platform != "win32":
    _ld = os.environ.get("LD_LIBRARY_PATH", "")
    _missing = [p for p in _LD_PATHS if p not in _ld]
    if _missing:
        os.environ["LD_LIBRARY_PATH"] = os.pathsep.join(
            _LD_PATHS + ([_ld] if _ld else [])
        )
        os.execv(sys.executable, [sys.executable] + sys.argv)
else:
    for p in _LD_PATHS:
        os.add_dll_directory(p)

# 3. If run as a script, exec the target
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python build/env.py <script.py> [args...]")
        sys.exit(1)
    script = sys.argv[1]
    sys.argv = sys.argv[1:]  # shift so script sees correct argv
    with open(script) as f:
        code = compile(f.read(), script, "exec")
    exec(code, {"__name__": "__main__", "__file__": os.path.abspath(script)})
''')
    env_py.chmod(0o755)
    print(f"Generated {env_py}")

if __name__ == "__main__":
    main()
